name: YouTube Downloader

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'لینک کامل YouTube'
        required: true
        type: string

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y ffmpeg python3-pip
        pip install yt-dlp --upgrade
        
    - name: Download with yt-dlp (bypass)
      run: |
        yt-dlp \
          --extracter-args "youtube:player_client=web" \
          --add-header "User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36" \
          --add-header "Accept-Language:en-US,en;q=0.9" \
          --no-check-certificate \
          --retries 10 \
          --fragment-retries 10 \
          --sleep-requests 1 \
          --sleep-interval 5 \
          --max-sleep-interval 15 \
          --limit-rate 2M \
          -f "best[ext=mp4]" \
          -o "video.mp4" \
          "${{ github.event.inputs.url }}"
          
    - name: Upload video
      uses: actions/upload-artifact@v4
      with:
        name: my-video
        path: ./video.mp4
