name: YouTube Downloader

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'لینک YouTube'
        required: true
        type: string

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
    - name: Install yt-dlp
      run: |
        sudo apt update
        sudo apt install -y ffmpeg
        pip install yt-dlp
        
    - name: Download Video
      run: |
        yt-dlp --no-check-certificate --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36" -f "best[ext=mp4]" -o "video.mp4" "${{ github.event.inputs.url }}"
        
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: video
        path: ./video.mp4
